name: project_fees
description: "A new Flutter project."
publish_to: 'none' # Prevents publishing to pub.dev by default

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0" # Update to ensure compatibility

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0
  http: 1.2.2
  file_picker: ^5.0.1
  path: ^1.9.0
  html: ^0.15.0
  intl: ^0.17.0
  shared_preferences: ^2.0.17
  data_table_2: ^2.5.8
  pdf: ^3.10.7
  path_provider: ^2.1.1
  open_file: ^3.3.2
  excel: ^2.0.4
  universal_html: ^2.0.10 

  #devtools: ^2.12.0
  # Firebase Core for initialization
  #firebase_core: ^3.8.0  # Use the latest version (check pub.dev for the latest stable version)
  
  # Firebase Authentication for user management
  #firebase_auth: ^5.3.3  # Use the latest version (check pub.dev for the latest stable version)
  logger: ^1.4.0
  # Optionally, add other Firebase packages you need
  # cloud_firestore: ^5.0.0  # Uncomment if you are using Firestore
  # firebase_storage: ^11.0.0  # Uncomment if you are using Firebase Storage
  
  flutter_test:
    sdk: flutter  # Test dependency
  
  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # Linting package for good coding practices
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

  # You can add asset files (e.g., images) to your app if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
